
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accesscontrolmanager
    username: root
    password: ok
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full

logging:
  level:
    root: info
    com.kgc.mapper: debug
  config: classpath:lombok-spring.xml